server:
  port: 9000
spring:
  application:
    name: "cards"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "prod"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest