server:
    port: 8090
Spring:
  application:
      name :loan-service
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password: ''
  h2:
      console.enabled: true
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  config:
    import:
      - "application_qa.yaml"
      - "application_prod.yaml"
  profiles:
    active:
      - "qa"
build:
  version: "3.0"

loans:
  message: "Welcome to myBank loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@mybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934