server:
    port: 8090
Spring:
  application:
      name :loan-service
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password: ''
  h2:
      console.enabled: true
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
