server:
    port: 8080
spring:
    application:
        name: accounts-service
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: ''
        driver-class-name: org.h2.Driver
    h2:
        console.enabled: true
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
    config:
        import:
            - "application_qa.yaml"
            - "application_prod.yaml"
    profiles:
        active:
            - "qa"
build:
    version: "3.0"
accounts:
    message: "Welcome to MyBank accounts related local APIs "
    contactDetails:
        name: "John Doe - Developer"
        email: "john@myBank.com"
    onCallSupport:
        - (555) 555-1234
        - (555) 523-1345
